swagger: '2.0'
info:
  title: Conversation Upload API
  description: API for handling conversation uploads
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /upload:
    post:
      summary: Upload conversation data
      operationId: uploadConversation
      responses:
        '200':
          description: Successful upload
          schema:
            type: object
            properties:
              message:
                type: string
      x-google-backend:
        address: [YOUR_CLOUD_FUNCTION_OR_CLOUD_RUN_URL]
        protocol: h2
security:
  - api_key: []
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query 