apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: convo-upload-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: "/health"
    port: 8080  

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: convo-summary-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: "/health"
    port: 8000 
