apiVersion: v1
kind: Service
metadata:
  name: convo-upload-service
spec:
  type: LoadBalancer
  selector:
    app: convo-upload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  
---
apiVersion: v1
kind: Service
metadata:
  name: convo-summary-service
spec:
  selector:
    app: convo-summary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer